main:
  - name: Bio
    url: /
    weight: 10
  - name: About
    url: about/
    weight: 15
  - name: Projects
    url: projects/
    weight: 20
  - name: Skills
    url: skills/
    weight: 25
  - name: Experience
    url: /#experience
    weight: 30